[package]
name = "localtool"
version = "0.1.1"
edition = "2021"
authors = ["Yared Getachew"]
repository = "https://github.com/veduket/localtool"
homepage = "https://localtool.vercel.app"
license = "MIT"
description = "Local development toolkit — DNS management and HTTPS certificates"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
local-dns = { path = "../local-dns", version = "0.1.1" }
local-ssl = { path = "../local-ssl", version = "0.1.1" }
